ci:
  autofix_commit_msg: "style: auto fix by pre-commit hooks"
  autofix_prs: false
  autoupdate_branch: main
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "chore: auto update by pre-commit hooks"


repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8  # 代码风格检查
        args: ["--max-line-length=120", "--extend-ignore=W503,E203"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy # mypy 类型检查
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
        additional_dependencies: ["types-PyYAML", "azure-ai-inference", "dashscope", "google-genai", "ollama"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--config=./pyproject.toml"]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # 版本号
    hooks:
      - id: trailing-whitespace  # 删除行尾空格